/**
 * Unified Response Types for Hybrid AI Approach
 * 
 * This module defines the standardized response schemas that all AI services
 * must return, ensuring consistent data flow and proper project ID tracking.
 */

// ============================================================================
// CORE RESPONSE INTERFACES
// ============================================================================

/**
 * Base response interface that all AI responses must extend
 * Ensures project ID is always included for proper user tracking
 */
export interface BaseAIResponse {
  /** Project ID for tracking responses back to specific users */
  projectId: string;
  /** Timestamp when the response was generated */
  timestamp: string;
  /** Success status of the AI operation */
  success: boolean;
  /** Error message if operation failed */
  error?: string;
}

/**
 * Regional Analysis Response
 * Generated by the regional analysis service
 */
export interface RegionalAnalysisResponse extends BaseAIResponse {
  /** Type identifier for response routing */
  type: 'regional_analysis';
  /** Regional context data */
  data: {
    cityState: string;
    primaryClassification: 'Hurricane Zone' | 'Earthquake Zone' | 'Tornado Alley' | 'Standard Region';
    secondaryClassifications: string[];
    climateZone: string;
    seasonalFactors: {
      winterLimitations: boolean;
      summerChallenges: boolean;
      rainySeason: string | null;
      optimalConstructionMonths: string[];
    };
    regulatoryEnvironment: {
      permitComplexity: 'Low' | 'Medium' | 'High';
      inspectionFrequency: 'Standard' | 'Enhanced' | 'Minimal';
      codeStrictness: 'Standard' | 'Strict' | 'Lenient';
      specialRequirements: string[];
    };
    marketConditions: {
      laborAvailability: 'High' | 'Medium' | 'Low';
      materialCosts: 'Below Average' | 'Average' | 'Above Average';
      contractorAvailability: 'High' | 'Medium' | 'Low';
      permitTimeline: 'Fast' | 'Standard' | 'Slow';
    };
    multipliers: {
      weatherDependent: number;
      permitComplexity: number;
      laborAvailability: number;
      materialCosts: number;
    };
    recommendations: string[];
  };
}

/**
 * Project Context Response
 * Generated by the project context service
 */
export interface ProjectContextResponse extends BaseAIResponse {
  /** Type identifier for response routing */
  type: 'project_context';
  /** Project context data */
  data: {
    projectDetails: {
      houseSize: number;
      foundationType: string;
      numberOfStories: number;
      constructionMethod: string;
      targetStartDate: string | null;
    };
    timelinePreference: 'Accelerated' | 'Standard' | 'Flexible';
    budgetRange: 'Budget' | 'Mid-Range' | 'Premium';
    projectComplexity: 'Simple' | 'Moderate' | 'Complex';
    regionalContext: {
      cityState: string;
      primaryClassification: string;
      multipliers: Record<string, number>;
    };
  };
}

/**
 * Phase-Specific Response
 * Generated by individual phase prompt services
 */
export interface PhaseSpecificResponse extends BaseAIResponse {
  /** Type identifier for response routing */
  type: 'phase_specific';
  /** Phase-specific data */
  data: {
    phaseId: string;
    phaseTitle: string;
    constructionMethod: string;
    timeline: {
      diyDuration: string | null;
      contractorDuration: string | null;
      diyHours: string | null;
      rawTimeline: string;
    };
    tasks: {
      steps: string[];
      qaChecks: string[];
      vendorQuestions: string[];
      vendorNeeds: string[];
    };
    helpfulInformation: {
      steps: string[];
      qaChecks: string[];
      vendorQuestions: string[];
      vendorNeeds: string[];
    };
    regionalAdjustments: {
      weatherConsiderations: string[];
      permitRequirements: string[];
      localVendorRecommendations: string[];
      seasonalTiming: string[];
    };
    expertInsights: {
      commonMistakes: string[];
      proTips: string[];
      costSavingTips: string[];
      qualityCheckpoints: string[];
    };
  };
}

/**
 * Main Roadmap Response
 * Generated by the main roadmap service
 */
export interface MainRoadmapResponse extends BaseAIResponse {
  /** Type identifier for response routing */
  type: 'main_roadmap';
  /** Main roadmap data */
  data: {
    phases: Array<{
      id: string;
      title: string;
      order: number;
      dependencies: string[];
      tasks: Array<{
        title: string;
        steps: string[];
        qaChecks: string[];
        vendorQuestions: string[];
        vendorNeeds: string[];
      }>;
      helpfulInformation: {
        steps: string[];
        qaChecks: string[];
        vendorQuestions: string[];
        vendorNeeds: string[];
      };
    }>;
    overallTimeline: {
      totalDuration: string;
      criticalPath: string[];
      milestones: Array<{
        phase: string;
        date: string;
        dependencies: string[];
      }>;
    };
    recommendations: {
      phaseOrdering: string[];
      riskMitigation: string[];
      resourceAllocation: string[];
    };
  };
}

// ============================================================================
// RESPONSE AGGREGATION TYPES
// ============================================================================

/**
 * Complete project response containing all AI-generated data
 * This is what gets stored in the database and sent to the frontend
 */
export interface CompleteProjectResponse {
  /** Project ID for tracking */
  projectId: string;
  /** User ID for ownership */
  userId: string;
  /** Timestamp when complete response was assembled */
  timestamp: string;
  /** Regional analysis data */
  regionalAnalysis: RegionalAnalysisResponse['data'];
  /** Project context data */
  projectContext: ProjectContextResponse['data'];
  /** Main roadmap data */
  mainRoadmap: MainRoadmapResponse['data'];
  /** Phase-specific responses */
  phaseResponses: PhaseSpecificResponse['data'][];
  /** Metadata */
  metadata: {
    totalPhases: number;
    completedPhases: number;
    lastUpdated: string;
    version: string;
  };
}

/**
 * Response assembly status for tracking parallel processing
 */
export interface ResponseAssemblyStatus {
  projectId: string;
  userId: string;
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  completedServices: string[];
  pendingServices: string[];
  errors: Array<{
    service: string;
    error: string;
    timestamp: string;
  }>;
  startedAt: string;
  completedAt?: string;
}

// ============================================================================
// RESPONSE PARSING UTILITIES
// ============================================================================

/**
 * Type guard to check if a response is a valid BaseAIResponse
 */
export function isBaseAIResponse(response: any): response is BaseAIResponse {
  return (
    typeof response === 'object' &&
    response !== null &&
    typeof response.projectId === 'string' &&
    typeof response.timestamp === 'string' &&
    typeof response.success === 'boolean'
  );
}

/**
 * Type guard to check if a response is a RegionalAnalysisResponse
 */
export function isRegionalAnalysisResponse(response: any): response is RegionalAnalysisResponse {
  return (
    isBaseAIResponse(response) &&
    response.type === 'regional_analysis' &&
    typeof response.data === 'object'
  );
}

/**
 * Type guard to check if a response is a ProjectContextResponse
 */
export function isProjectContextResponse(response: any): response is ProjectContextResponse {
  return (
    isBaseAIResponse(response) &&
    response.type === 'project_context' &&
    typeof response.data === 'object'
  );
}

/**
 * Type guard to check if a response is a PhaseSpecificResponse
 */
export function isPhaseSpecificResponse(response: any): response is PhaseSpecificResponse {
  return (
    isBaseAIResponse(response) &&
    response.type === 'phase_specific' &&
    typeof response.data === 'object' &&
    typeof response.data.phaseId === 'string'
  );
}

/**
 * Type guard to check if a response is a MainRoadmapResponse
 */
export function isMainRoadmapResponse(response: any): response is MainRoadmapResponse {
  return (
    isBaseAIResponse(response) &&
    response.type === 'main_roadmap' &&
    typeof response.data === 'object'
  );
}

// ============================================================================
// RESPONSE VALIDATION
// ============================================================================

/**
 * Validates that a response contains all required fields
 */
export function validateResponse(response: any): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!isBaseAIResponse(response)) {
    errors.push('Response must extend BaseAIResponse');
    return { valid: false, errors };
  }

  if (!response.projectId || typeof response.projectId !== 'string') {
    errors.push('Project ID is required and must be a string');
  }

  if (!response.timestamp || typeof response.timestamp !== 'string') {
    errors.push('Timestamp is required and must be a string');
  }

  if (typeof response.success !== 'boolean') {
    errors.push('Success field is required and must be a boolean');
  }

  if (response.success === false && !response.error) {
    errors.push('Error message is required when success is false');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

// ============================================================================
// RESPONSE CREATION HELPERS
// ============================================================================

/**
 * Creates a base response with common fields
 */
export function createBaseResponse(projectId: string, success: boolean = true, error?: string): BaseAIResponse {
  return {
    projectId,
    timestamp: new Date().toISOString(),
    success,
    error
  };
}

/**
 * Creates a successful response with data
 */
export function createSuccessResponse<T extends BaseAIResponse>(
  projectId: string,
  type: T['type'],
  data: T['data']
): T {
  return {
    ...createBaseResponse(projectId, true),
    type,
    data
  } as T;
}

/**
 * Creates an error response
 */
export function createErrorResponse<T extends BaseAIResponse>(
  projectId: string,
  type: T['type'],
  error: string
): T {
  return {
    ...createBaseResponse(projectId, false, error),
    type,
    data: {} as T['data']
  } as T;
}
